import { Activity, Center, Quest, Badge, Reward, Suggestion, LeaderboardEntry, VolunteerAssignment, Notification, ProjectSuggestion } from './types';

export const mockCenters: Center[] = [
  {
    id: '1',
    name: 'دار الشباب المركزي',
    wilaya: 'الجزائر',
    address: 'حي بئر مراد رايس',
    lat: 36.7538,
    lng: 3.0588,
    distance: 1.2,
    eta: 15,
    rating: 4.5,
    capacity: 300,
  },
  {
    id: '2',
    name: 'دار الشباب وهران',
    wilaya: 'وهران',
    address: 'حي السانيا',
    lat: 35.6976,
    lng: -0.6337,
    distance: 2.5,
    eta: 25,
    rating: 4.7,
    capacity: 250,
  },
  {
    id: '3',
    name: 'دار الشباب قسنطينة',
    wilaya: 'قسنطينة',
    address: 'وسط المدينة',
    lat: 36.3650,
    lng: 6.6147,
    distance: 3.0,
    eta: 30,
    rating: 4.6,
    capacity: 200,
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    title: 'ورشة البرمجة للمبتدئين',
    description: 'تعلم أساسيات البرمجة مع Python في بيئة تفاعلية',
    centerId: '1',
    centerName: 'دار الشباب المركزي',
    category: 'learning',
    type: 'free',
    date: '2025-11-08',
    time: '14:00',
    duration: 120,
    capacity: 30,
    registered: 22,
    waitlist: 5,
    instructor: 'أ. محمد بن علي',
  },
  {
    id: '2',
    title: 'بطولة كرة القدم الخماسية',
    description: 'دوري شبابي أسبوعي - سجل فريقك الآن',
    centerId: '1',
    centerName: 'دار الشباب المركزي',
    category: 'sports',
    type: 'paid',
    price: 500,
    date: '2025-11-10',
    time: '16:00',
    duration: 180,
    capacity: 40,
    registered: 35,
    waitlist: 8,
  },
  {
    id: '3',
    title: 'حملة تنظيف الشاطئ',
    description: 'مبادرة بيئية لتنظيف الشواطئ المحلية',
    centerId: '2',
    centerName: 'دار الشباب وهران',
    category: 'environmental',
    type: 'free',
    date: '2025-11-12',
    time: '08:00',
    duration: 240,
    capacity: 50,
    registered: 18,
    waitlist: 0,
  },
  {
    id: '4',
    title: 'ندوة القيادة الشبابية',
    description: 'لقاء تفاعلي مع قادة محليين ومتحدثين ملهمين',
    centerId: '3',
    centerName: 'دار الشباب قسنطينة',
    category: 'social',
    type: 'virtual',
    date: '2025-11-15',
    time: '18:00',
    duration: 90,
    capacity: 200,
    registered: 145,
    waitlist: 0,
  },
  {
    id: '5',
    title: 'بطولة الرياضات ��لإلكترونية',
    description: 'مسابقة FIFA 24 - جوائز قيمة للفائزين',
    centerId: '1',
    centerName: 'دار الشباب المركزي',
    category: 'e-sport',
    type: 'free',
    date: '2025-11-20',
    time: '15:00',
    duration: 300,
    capacity: 32,
    registered: 28,
    waitlist: 12,
  },
];

export const mockQuests: Quest[] = [
  {
    id: '1',
    title: 'مبتدئ النشاط',
    description: 'سجل في نشاط واحد هذا الأسبوع',
    type: 'weekly',
    progress: 1,
    total: 1,
    reward: 50,
    completed: true,
  },
  {
    id: '2',
    title: 'الحضور المثالي',
    description: 'احضر 3 أنشطة هذا الأسبوع',
    type: 'weekly',
    progress: 2,
    total: 3,
    reward: 100,
    completed: false,
  },
  {
    id: '3',
    title: 'المتطوع النشط',
    description: 'ساهم بـ 5 ساعات تطوع',
    type: 'seasonal',
    progress: 3,
    total: 5,
    reward: 200,
    completed: false,
  },
  {
    id: '4',
    title: 'المقترح المبدع',
    description: 'قدم اقتراحاً يحصل على 10 أصوات',
    type: 'seasonal',
    progress: 7,
    total: 10,
    reward: 150,
    completed: false,
  },
];

export const mockBadges: Badge[] = [
  {
    id: '1',
    name: 'مبتدئ',
    description: 'أكمل أول نشاط',
    icon: 'award',
    tier: 'Bronze',
    earned: true,
    earnedAt: '2025-10-15',
  },
  {
    id: '2',
    name: 'رياضي',
    description: 'شارك في 5 أنشطة رياضية',
    icon: 'trophy',
    tier: 'Silver',
    earned: true,
    earnedAt: '2025-10-28',
  },
  {
    id: '3',
    name: 'متعلم',
    description: 'أكمل 10 ورش تعليمية',
    icon: 'graduation-cap',
    tier: 'Gold',
    earned: false,
    fragments: 6,
    totalFragments: 10,
  },
  {
    id: '4',
    name: 'قائد المجتمع',
    description: 'تطوع لأكثر من 50 ساعة',
    icon: 'users',
    tier: 'Platinum',
    earned: false,
    fragments: 2,
    totalFragments: 50,
  },
];

export const mockRewards: Reward[] = [
  {
    id: '1',
    title: 'حجز أولوية',
    description: 'احجز مقعداً قبل الجميع',
    category: 'priority',
    cost: 100,
    available: true,
  },
  {
    id: '2',
    title: 'قسيمة مطعم',
    description: 'خصم 50% في مطاعم محددة',
    category: 'voucher',
    cost: 300,
    available: true,
  },
  {
    id: '3',
    title: 'إعارة معدات رياضية',
    description: 'استعر معدات رياضية لمدة أسبوع',
    category: 'equipment',
    cost: 150,
    available: true,
  },
  {
    id: '4',
    title: 'تذكرة ورشة متقدمة',
    description: 'وصول حصري لورشة متقدمة',
    category: 'priority',
    cost: 500,
    available: false,
  },
];

export const mockSuggestions: Suggestion[] = [
  {
    id: '1',
    userId: '1',
    userName: 'أحمد محمد',
    title: 'ورشة تصوير فوتوغرافي',
    description: 'نحتاج لورشة تعليم التصوير الفوتوغرافي للمبتدئين',
    category: 'learning',
    wilaya: 'الجزائر',
    votes: 47,
    votedBy: ['2', '3', '4'],
    status: 'approved',
    createdAt: '2025-10-25',
    comments: [
      {
        id: '1',
        userId: '2',
        userName: 'فاطمة علي',
        text: 'فكرة ممتازة! أنا مهتمة',
        createdAt: '2025-10-26',
      },
    ],
  },
  {
    id: '2',
    userId: '2',
    userName: 'سارة خالد',
    title: 'نادي الكتاب الشهري',
    description: 'لقاء شهري لمناقشة كتاب محدد',
    category: 'social',
    wilaya: 'وهران',
    votes: 32,
    votedBy: ['1', '3'],
    status: 'pending',
    createdAt: '2025-10-30',
    comments: [],
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: '1',
    userName: 'أحمد محمد',
    points: 1850,
    level: 'Platinum',
    wilaya: 'الجزائر',
    age: 22,
    field: 'learning',
  },
  {
    rank: 2,
    userId: '2',
    userName: 'فاطمة علي',
    points: 1720,
    level: 'Gold',
    wilaya: 'وهران',
    age: 20,
    field: 'sports',
  },
  {
    rank: 3,
    userId: '3',
    userName: 'محمد حسن',
    points: 1580,
    level: 'Gold',
    wilaya: 'قسنطينة',
    age: 24,
    field: 'environmental',
  },
  {
    rank: 4,
    userId: '4',
    userName: 'سارة خالد',
    points: 1420,
    level: 'Silver',
    wilaya: 'عنابة',
    age: 21,
    field: 'social',
  },
  {
    rank: 5,
    userId: '5',
    userName: 'يوسف أحمد',
    points: 1250,
    level: 'Silver',
    wilaya: 'الجزائر',
    age: 19,
    field: 'e-sport',
  },
];

export const mockVolunteerAssignments: VolunteerAssignment[] = [
  {
    id: '1',
    activityId: '1',
    activityTitle: 'ورشة البرمجة للمبتدئين',
    date: '2025-11-08',
    time: '14:00',
    hours: 2,
    status: 'upcoming',
  },
  {
    id: '2',
    activityId: '3',
    activityTitle: 'حملة تنظيف الشاطئ',
    date: '2025-11-12',
    time: '08:00',
    hours: 4,
    status: 'upcoming',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'reminder',
    title: 'تذكير: نشاطك القادم',
    message: 'ورشة البرمجة للمبتدئين تبدأ غداً في تمام الساعة 14:00',
    read: false,
    createdAt: '2025-11-01 10:00',
    actionUrl: '/activity/1',
  },
  {
    id: '2',
    type: 'achievement',
    title: 'إنجاز جديد!',
    message: 'لقد حصلت على شارة "رياضي"',
    read: false,
    createdAt: '2025-10-28 16:30',
  },
  {
    id: '3',
    type: 'announcement',
    title: 'إعلان',
    message: 'بطولة الرياضات الإلكترونية - التسجيل مفتوح الآن',
    read: true,
    createdAt: '2025-10-25 09:00',
  },
];

export const mockProjectSuggestions: ProjectSuggestion[] = [
  {
    id: '1',
    userId: '1',
    userName: 'أحمد محمد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    title: 'مختبر الروبوتات للشباب',
    description: 'إنشاء مختبر مجهز بأدوات الروبوتات والإلكترونيات حيث يمكن للشباب تعلم البرمجة وبناء روبوتات بسيطة. سيشمل المختبر ورش عمل أسبوعية ومسابقات شهرية.',
    category: 'technology',
    targetAudience: 'الشباب 15-25 سنة',
    estimatedCost: '250,000 دج',
    duration: '3 أشهر',
    votes: 142,
    votedBy: ['2', '3', '4', '5'],
    status: 'under_review',
    createdAt: '2025-10-20',
    updatedAt: '2025-11-01',
    wilaya: 'الجزائر',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400',
    comments: [
      {
        id: '1',
        userId: '2',
        userName: 'فاطمة علي',
        text: 'فكرة رائعة! نحتاج هذا النوع من المختبرات',
        createdAt: '2025-10-21',
      },
      {
        id: '2',
        userId: '3',
        userName: 'محمد حسن',
        text: 'أنا مهتم بالمساعدة في هذا المشروع',
        createdAt: '2025-10-22',
      },
    ],
  },
  {
    id: '2',
    userId: '2',
    userName: 'سارة خالد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
    title: 'مركز الفنون والحرف اليدوية',
    description: 'مركز مخصص لتعليم الفنون التقليدية الجزائرية والحرف اليدوية مثل الخزف والنسيج والرسم. سيوفر المركز دورات تدريبية مع حرفيين محليين.',
    category: 'arts',
    targetAudience: 'جميع الأعمار',
    estimatedCost: '150,000 دج',
    duration: '2 أشهر',
    votes: 98,
    votedBy: ['1', '4'],
    status: 'pending',
    createdAt: '2025-10-25',
    updatedAt: '2025-10-28',
    wilaya: 'وهران',
    thumbnail: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    comments: [],
  },
  {
    id: '3',
    userId: '3',
    userName: 'يوسف أحمد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Youssef',
    title: 'حديقة حضرية مجتمعية',
    description: 'تحويل مساحة غير مستخدمة إلى حديقة حضرية حيث يمكن للشباب زراعة الخضروات والنباتات. المشروع يعزز الوعي البيئي ويوفر مساحة خضراء للمجتمع.',
    category: 'environmental',
    targetAudience: 'الشباب والعائلات',
    estimatedCost: '100,000 دج',
    duration: '4 أشهر',
    votes: 87,
    votedBy: ['1', '2', '5'],
    status: 'approved',
    createdAt: '2025-10-15',
    updatedAt: '2025-10-30',
    wilaya: 'قسنطينة',
    thumbnail: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400',
    comments: [
      {
        id: '3',
        userId: '5',
        userName: 'ليلى بن علي',
        text: 'مشروع مهم للبيئة والمجتمع',
        createdAt: '2025-10-16',
      },
    ],
  },
  {
    id: '4',
    userId: '4',
    userName: 'خالد الطاهر',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Khaled',
    title: 'أكاديمية الرياضات الإلكترونية',
    description: 'إنشاء أكاديمية متخصصة في تدريب اللاعبين المحترفين للرياضات الإلكترونية مع معدات حديثة ومدربين معتمدين. ستشمل بطولات محلية ووطنية.',
    category: 'e-sport',
    targetAudience: 'الشباب 14-30 سنة',
    estimatedCost: '300,000 دج',
    duration: '6 أشهر',
    votes: 156,
    votedBy: ['1', '2', '3'],
    status: 'under_review',
    createdAt: '2025-10-18',
    updatedAt: '2025-11-02',
    wilaya: 'الجزائر',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400',
    comments: [
      {
        id: '4',
        userId: '1',
        userName: 'أحمد محمد',
        text: 'نحتاج هذا بشدة! الرياضات الإلكترونية تنمو بسرعة',
        createdAt: '2025-10-19',
      },
    ],
  },
  {
    id: '5',
    userId: '5',
    userName: 'ليلى بن علي',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Layla',
    title: 'برنامج ريادة الأعمال للشباب',
    description: 'برنامج تدريبي شامل لتعليم الشباب مهارات ريادة الأعمال، من التخطيط إلى التنفيذ. يتضمن ورش عمل، إرشاد من رواد أعمال ناجحين، ومسابقة لأفضل فكرة مشروع.',
    category: 'entrepreneurship',
    targetAudience: 'الشباب 18-35 سنة',
    estimatedCost: '200,000 دج',
    duration: '5 أشهر',
    votes: 73,
    votedBy: ['2', '4'],
    status: 'pending',
    createdAt: '2025-10-28',
    updatedAt: '2025-10-29',
    wilaya: 'عنابة',
    thumbnail: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?w=400',
    comments: [],
  },
  {
    id: '6',
    userId: '1',
    userName: 'أحمد محمد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    title: 'نادي السينما والإنتاج السمعي البصري',
    description: 'نادي لتعليم فنون الإخراج والتصوير السينمائي والمونتاج. سيضم معدات احترافية وورش عمل مع مخرجين محليين، وسينتج أفلام قصيرة شهرياً.',
    category: 'arts',
    targetAudience: 'الشباب 16-28 سنة',
    estimatedCost: '180,000 دج',
    duration: '3 أشهر',
    votes: 64,
    votedBy: ['3', '5'],
    status: 'pending',
    createdAt: '2025-10-30',
    updatedAt: '2025-10-31',
    wilaya: 'الجزائر',
    thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400',
    comments: [],
  },
];
