import { Activity, Center, Quest, Badge, Reward, Suggestion, LeaderboardEntry, VolunteerAssignment, Notification, ProjectSuggestion } from './types';

export const mockCenters: Center[] = [
  {
    id: '1',
    name: 'دار الشباب المركزي',
    wilaya: 'الجزائر',
    address: 'حي بئر مراد رايس',
    lat: 36.7538,
    lng: 3.0588,
    distance: 1.2,
    eta: 15,
    rating: 4.5,
    capacity: 300,
  },
  {
    id: '2',
    name: 'دار الشباب وهران',
    wilaya: 'وهران',
    address: 'حي السانيا',
    lat: 35.6976,
    lng: -0.6337,
    distance: 2.5,
    eta: 25,
    rating: 4.7,
    capacity: 250,
  },
  {
    id: '3',
    name: 'دار الشباب قسنطينة',
    wilaya: 'قسنطينة',
    address: 'وسط المدينة',
    lat: 36.3650,
    lng: 6.6147,
    distance: 3.0,
    eta: 30,
    rating: 4.6,
    capacity: 200,
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    title: 'ورشة البرمجة للمبتدئين',
    description: 'تعلم أساسيات البرمجة مع Python في بيئة تفاعلية',
    centerId: '1',
    centerName: 'دار الشباب المركزي',
    category: 'learning',
    type: 'free',
    date: '2025-11-08',
    time: '14:00',
    duration: 120,
    capacity: 30,
    registered: 22,
    waitlist: 5,
    instructor: 'أ. محمد بن علي',
  },
  {
    id: '2',
    title: 'بطولة كرة القدم الخماسية',
    description: 'دوري شبابي أسبوعي - سجل فريقك الآن',
    centerId: '1',
    centerName: 'دار الشباب المركزي',
    category: 'sports',
    type: 'paid',
    price: 500,
    date: '2025-11-10',
    time: '16:00',
    duration: 180,
    capacity: 40,
    registered: 35,
    waitlist: 8,
  },
  {
    id: '3',
    title: 'حملة تنظيف الشاطئ',
    description: 'مبادرة بيئية لتنظيف الشواطئ المحلية',
    centerId: '2',
    centerName: 'دار الشباب وهران',
    category: 'environmental',
    type: 'free',
    date: '2025-11-12',
    time: '08:00',
    duration: 240,
    capacity: 50,
    registered: 18,
    waitlist: 0,
  },
  {
    id: '4',
    title: 'ندوة القيادة الشبابية',
    description: 'لقاء تفاعلي مع قادة محليين ومتحدثين ملهمين',
    centerId: '3',
    centerName: 'دار الشباب قسنطينة',
    category: 'social',
    type: 'virtual',
    date: '2025-11-15',
    time: '18:00',
    duration: 90,
    capacity: 200,
    registered: 145,
    waitlist: 0,
  },
  {
    id: '5',
    title: 'بطولة الرياضات ��لإلكترونية',
    description: 'مسابقة FIFA 24 - جوائز قيمة للفائزين',
    centerId: '1',
    centerName: 'دار الشباب المركزي',
    category: 'e-sport',
    type: 'free',
    date: '2025-11-20',
    time: '15:00',
    duration: 300,
    capacity: 32,
    registered: 28,
    waitlist: 12,
  },
];

export const mockQuests: Quest[] = [
  {
    id: '1',
    title: 'مبتدئ النشاط',
    description: 'سجل في نشاط واحد هذا الأسبوع',
    type: 'weekly',
    progress: 1,
    total: 1,
    reward: 50,
    completed: true,
  },
  {
    id: '2',
    title: 'الحضور المثالي',
    description: 'احضر 3 أنشطة هذا الأسبوع',
    type: 'weekly',
    progress: 2,
    total: 3,
    reward: 100,
    completed: false,
  },
  {
    id: '3',
    title: 'المتطوع النشط',
    description: 'ساهم بـ 5 ساعات تطوع',
    type: 'seasonal',
    progress: 3,
    total: 5,
    reward: 200,
    completed: false,
  },
  {
    id: '4',
    title: 'المقترح المبدع',
    description: 'قدم اقتراحاً يحصل على 10 أصوات',
    type: 'seasonal',
    progress: 7,
    total: 10,
    reward: 150,
    completed: false,
  },
];

export const mockBadges: Badge[] = [
  {
    id: '1',
    name: 'مبتدئ',
    description: 'أكمل أول نشاط',
    icon: 'award',
    tier: 'Bronze',
    earned: true,
    earnedAt: '2025-10-15',
  },
  {
    id: '2',
    name: 'رياضي',
    description: 'شارك في 5 أنشطة رياضية',
    icon: 'trophy',
    tier: 'Silver',
    earned: true,
    earnedAt: '2025-10-28',
  },
  {
    id: '3',
    name: 'متعلم',
    description: 'أكمل 10 ورش تعليمية',
    icon: 'graduation-cap',
    tier: 'Gold',
    earned: false,
    fragments: 6,
    totalFragments: 10,
  },
  {
    id: '4',
    name: 'قائد المجتمع',
    description: 'تطوع لأكثر من 50 ساعة',
    icon: 'users',
    tier: 'Platinum',
    earned: false,
    fragments: 2,
    totalFragments: 50,
  },
];

export const mockRewards: Reward[] = [
  {
    id: '1',
    title: 'حجز أولوية',
    description: 'احجز مقعداً قبل الجميع',
    category: 'priority',
    cost: 100,
    available: true,
  },
  {
    id: '2',
    title: 'قسيمة مطعم',
    description: 'خصم 50% في مطاعم محددة',
    category: 'voucher',
    cost: 300,
    available: true,
  },
  {
    id: '3',
    title: 'إعارة معدات رياضية',
    description: 'استعر معدات رياضية لمدة أسبوع',
    category: 'equipment',
    cost: 150,
    available: true,
  },
  {
    id: '4',
    title: 'تذكرة ورشة متقدمة',
    description: 'وصول حصري لورشة متقدمة',
    category: 'priority',
    cost: 500,
    available: false,
  },
];

export const mockSuggestions: Suggestion[] = [
  {
    id: '1',
    userId: '1',
    userName: 'أحمد محمد',
    title: 'ورشة تصوير فوتوغرافي',
    description: 'نحتاج لورشة تعليم التصوير الفوتوغرافي للمبتدئين',
    category: 'learning',
    wilaya: 'الجزائر',
    votes: 47,
    votedBy: ['2', '3', '4'],
    status: 'approved',
    createdAt: '2025-10-25',
    comments: [
      {
        id: '1',
        userId: '2',
        userName: 'فاطمة علي',
        text: 'فكرة ممتازة! أنا مهتمة',
        createdAt: '2025-10-26',
      },
    ],
  },
  {
    id: '2',
    userId: '2',
    userName: 'سارة خالد',
    title: 'نادي الكتاب الشهري',
    description: 'لقاء شهري لمناقشة كتاب محدد',
    category: 'social',
    wilaya: 'وهران',
    votes: 32,
    votedBy: ['1', '3'],
    status: 'pending',
    createdAt: '2025-10-30',
    comments: [],
  },
];

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: '1',
    userName: 'أحمد محمد',
    points: 1850,
    level: 'Platinum',
    wilaya: 'الجزائر',
    age: 22,
    field: 'learning',
  },
  {
    rank: 2,
    userId: '2',
    userName: 'فاطمة علي',
    points: 1720,
    level: 'Gold',
    wilaya: 'وهران',
    age: 20,
    field: 'sports',
  },
  {
    rank: 3,
    userId: '3',
    userName: 'محمد حسن',
    points: 1580,
    level: 'Gold',
    wilaya: 'قسنطينة',
    age: 24,
    field: 'environmental',
  },
  {
    rank: 4,
    userId: '4',
    userName: 'سارة خالد',
    points: 1420,
    level: 'Silver',
    wilaya: 'عنابة',
    age: 21,
    field: 'social',
  },
  {
    rank: 5,
    userId: '5',
    userName: 'يوسف أحمد',
    points: 1250,
    level: 'Silver',
    wilaya: 'الجزائر',
    age: 19,
    field: 'e-sport',
  },
];

export const mockVolunteerAssignments: VolunteerAssignment[] = [
  {
    id: '1',
    activityId: '1',
    activityTitle: 'ورشة البرمجة للمبتدئين',
    date: '2025-11-08',
    time: '14:00',
    hours: 2,
    status: 'upcoming',
  },
  {
    id: '2',
    activityId: '3',
    activityTitle: 'حملة تنظيف الشاطئ',
    date: '2025-11-12',
    time: '08:00',
    hours: 4,
    status: 'upcoming',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'reminder',
    title: 'تذكير: نشاطك القادم',
    message: 'ورشة البرمجة للمبتدئين تبدأ غداً في تمام الساعة 14:00',
    read: false,
    createdAt: '2025-11-01 10:00',
    actionUrl: '/activity/1',
  },
  {
    id: '2',
    type: 'achievement',
    title: 'إنجاز جديد!',
    message: 'لقد حصلت على شارة "رياضي"',
    read: false,
    createdAt: '2025-10-28 16:30',
  },
  {
    id: '3',
    type: 'announcement',
    title: 'إعلان',
    message: 'بطولة الرياضات الإلكترونية - التسجيل مفتوح الآن',
    read: true,
    createdAt: '2025-10-25 09:00',
  },
];

export const mockProjectSuggestions: ProjectSuggestion[] = [
  {
    id: '1',
    userId: '1',
    userName: 'أحمد محمد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    title: 'مختبر الروبوتات للشباب',
    description: 'إنشاء مختبر مجهز بأدوات الروبوتات والإلكترونيات حيث يمكن للشباب تعلم البرمجة وبناء روبوتات بسيطة. سيشمل المختبر ورش عمل أسبوعية ومسابقات شهرية.',
    category: 'technology',
    targetAudience: 'الشباب 15-25 سنة',
    estimatedCost: '250,000 دج',
    duration: '3 أشهر',
    votes: 142,
    votedBy: ['2', '3', '4', '5'],
    status: 'under_review',
    createdAt: '2025-10-20',
    updatedAt: '2025-11-01',
    wilaya: 'الجزائر',
    thumbnail: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400',
    comments: [
      {
        id: '1',
        userId: '2',
        userName: 'فاطمة علي',
        text: 'فكرة رائعة! نحتاج هذا النوع من المختبرات',
        createdAt: '2025-10-21',
      },
      {
        id: '2',
        userId: '3',
        userName: 'محمد حسن',
        text: 'أنا مهتم بالمساعدة في هذا المشروع',
        createdAt: '2025-10-22',
      },
    ],
  },
  {
    id: '2',
    userId: '2',
    userName: 'سارة خالد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
    title: 'مركز الفنون والحرف اليدوية',
    description: 'مركز مخصص لتعليم الفنون التقليدية الجزائرية والحرف اليدوية مثل الخزف والنسيج والرسم. سيوفر المركز دورات تدريبية مع حرفيين محليين.',
    category: 'arts',
    targetAudience: 'جميع الأعمار',
    estimatedCost: '150,000 دج',
    duration: '2 أشهر',
    votes: 98,
    votedBy: ['1', '4'],
    status: 'pending',
    createdAt: '2025-10-25',
    updatedAt: '2025-10-28',
    wilaya: 'وهران',
    thumbnail: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    comments: [],
  },
  {
    id: '3',
    userId: '3',
    userName: 'يوسف أحمد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Youssef',
    title: 'حديقة حضرية مجتمعية',
    description: 'تحويل مساحة غير مستخدمة إلى حديقة حضرية حيث يمكن للشباب زراعة الخضروات والنباتات. المشروع يعزز الوعي البيئي ويوفر مساحة خضراء للمجتمع.',
    category: 'environmental',
    targetAudience: 'الشباب والعائلات',
    estimatedCost: '100,000 دج',
    duration: '4 أشهر',
    votes: 87,
    votedBy: ['1', '2', '5'],
    status: 'approved',
    createdAt: '2025-10-15',
    updatedAt: '2025-10-30',
    wilaya: 'قسنطينة',
    thumbnail: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400',
    comments: [
      {
        id: '3',
        userId: '5',
        userName: 'ليلى بن علي',
        text: 'مشروع مهم للبيئة والمجتمع',
        createdAt: '2025-10-16',
      },
    ],
  },
  {
    id: '4',
    userId: '4',
    userName: 'خالد الطاهر',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Khaled',
    title: 'أكاديمية الرياضات الإلكترونية',
    description: 'إنشاء أكاديمية متخصصة في تدريب اللاعبين المحترفين للرياضات الإلكترونية مع معدات حديثة ومدربين معتمدين. ستشمل بطولات محلية ووطنية.',
    category: 'e-sport',
    targetAudience: 'الشباب 14-30 سنة',
    estimatedCost: '300,000 دج',
    duration: '6 أشهر',
    votes: 156,
    votedBy: ['1', '2', '3'],
    status: 'under_review',
    createdAt: '2025-10-18',
    updatedAt: '2025-11-02',
    wilaya: 'الجزائر',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400',
    comments: [
      {
        id: '4',
        userId: '1',
        userName: 'أحمد محمد',
        text: 'نحتاج هذا بشدة! الرياضات الإلكترونية تنمو بسرعة',
        createdAt: '2025-10-19',
      },
    ],
  },
  {
    id: '5',
    userId: '5',
    userName: 'ليلى بن علي',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Layla',
    title: 'برنامج ريادة الأعمال للشباب',
    description: 'برنامج تدريبي شامل لتعليم الشباب مهارات ريادة الأعمال، من التخطيط إلى التنفيذ. يتضمن ورش عمل، إرشاد من رواد أعمال ناجحين، ومسابقة لأفضل فكرة مشروع.',
    category: 'entrepreneurship',
    targetAudience: 'الشباب 18-35 سنة',
    estimatedCost: '200,000 دج',
    duration: '5 أشهر',
    votes: 73,
    votedBy: ['2', '4'],
    status: 'pending',
    createdAt: '2025-10-28',
    updatedAt: '2025-10-29',
    wilaya: 'عنابة',
    thumbnail: 'https://images.unsplash.com/photo-1556155092-490a1ba16284?w=400',
    comments: [],
  },
  {
    id: '6',
    userId: '1',
    userName: 'أحمد محمد',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    title: 'نادي السينما والإنتاج السمعي البصري',
    description: 'نادي لتعليم فنون الإخراج والتصوير السينمائي والمونتاج. سيضم معدات احترافية وورش عمل مع مخرجين محليين، وسينتج أفلام قصيرة شهرياً.',
    category: 'arts',
    targetAudience: 'الشباب 16-28 سنة',
    estimatedCost: '180,000 دج',
    duration: '3 أشهر',
    votes: 64,
    votedBy: ['3', '5'],
    status: 'pending',
    createdAt: '2025-10-30',
    updatedAt: '2025-10-31',
    wilaya: 'الجزائر',
    thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400',
    comments: [],
  },
];

export const mockClubs: Club[] = [
  // Support Clubs (دعم وتأهيل)
  {
    id: 'support-1',
    name: 'نادي الدعم للتغلب على الإدمان',
    description: 'مجموعة دعم آمنة للشباب الذين يواجهون تحديات الإدمان. نوفر بيئة آمنة ومهنية للمشاركة والدعم المتبادل مع مرشدين متخصصين.',
    category: 'support-addiction',
    coverImage: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=800&h=400&fit=crop',
    memberCount: 45,
    visibility: 'public',
    admins: ['admin-1'],
    moderators: ['mod-1', 'mod-2'],
    rules: [
      'السرية التامة للمعلومات المتبادلة',
      'الاحترام المتبادل بين جميع الأعضاء',
      'عدم التمييز أو الإساءة لأي عضو',
      'الحضور المنتظم للجلسات',
    ],
    centerId: '1',
  },
  {
    id: 'support-2',
    name: 'نادي الشباب ذوي الإعاقة',
    description: 'مجتمع داعم للشباب ذوي الإعاقات المختلفة. نركز على الدمج الاجتماعي، تطوير المهارات، والتوعية بحقوق الأشخاص ذوي الإعاقة.',
    category: 'support-disability',
    coverImage: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=800&h=400&fit=crop',
    memberCount: 62,
    visibility: 'public',
    admins: ['admin-2'],
    moderators: ['mod-3'],
    rules: [
      'الدعم والاحترام لجميع الأعضاء',
      'توفير بيئة شاملة ومتاحة للجميع',
      'التوعية بحقوق الأشخاص ذوي الإعاقة',
      'المشاركة الفعالة في الأنشطة',
    ],
    centerId: '1',
  },
  {
    id: 'support-3',
    name: 'مجموعة الدعم النفسي للشباب',
    description: 'مساحة آمنة لمناقشة التحديات النفسية والضغوط اليومية. جلسات دعم جماعي مع متخصصين في الصحة النفسية.',
    category: 'support-mental-health',
    coverImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=400&fit=crop',
    memberCount: 38,
    visibility: 'public',
    admins: ['admin-3'],
    moderators: ['mod-4'],
    rules: [
      'السرية التامة',
      'الاحترام والدعم غير المشروط',
      'عدم الحكم على الآخرين',
      'المشاركة الطوعية',
    ],
    centerId: '2',
  },
  {
    id: 'support-4',
    name: 'نادي التأهيل المهني',
    description: 'مساعدة الشباب في العثور على فرص عمل مناسبة وتطوير المهارات المهنية. ورش عمل، تدريب، وإرشاد وظيفي.',
    category: 'support-vocational',
    coverImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&h=400&fit=crop',
    memberCount: 89,
    visibility: 'public',
    admins: ['admin-4'],
    moderators: ['mod-5', 'mod-6'],
    rules: [
      'الالتزام بالحضور',
      'المشاركة الفعالة في التدريبات',
      'مساعدة الآخرين في التطوير',
      'الاحترام المهني',
    ],
    centerId: '2',
  },
  {
    id: 'support-5',
    name: 'مجموعة دعم الناجين من العنف',
    description: 'مساحة آمنة للشباب الناجين من العنف. دعم نفسي، قانوني، واجتماعي مع محترفين متخصصين.',
    category: 'support-violence-survivors',
    coverImage: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=400&fit=crop',
    memberCount: 34,
    visibility: 'private',
    admins: ['admin-5'],
    moderators: ['mod-7'],
    rules: [
      'السرية الكاملة',
      'الاحترام والأمان للجميع',
      'عدم الكشف عن هوية الأعضاء',
      'الدعم غير المشروط',
    ],
    centerId: '3',
  },
  
  // Normal Clubs (أندية عامة)
  {
    id: 'club-1',
    name: 'نادي القراءة',
    description: 'نادي للقراء الشباب لمناقشة الكتب، مشاركة التوصيات، وتنظيم لقاءات شهرية. نقرأ الأدب العربي والعالمي والكتب العلمية.',
    category: 'culture-books',
    coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=400&fit=crop',
    memberCount: 127,
    visibility: 'public',
    admins: ['admin-6'],
    moderators: ['mod-8', 'mod-9'],
    rules: [
      'قراءة الكتاب المختار شهرياً',
      'المشاركة في المناقشات',
      'الاحترام للآراء المختلفة',
      'عدم الإساءة للكتب أو المؤلفين',
    ],
    centerId: '1',
  },
  {
    id: 'club-2',
    name: 'نادي الروبوتات والذكاء الاصطناعي',
    description: 'نادي تقني للشباب المهتمين بالروبوتات، البرمجة، والذكاء الاصطناعي. مشاريع، مسابقات، وورش عمل تقنية.',
    category: 'technology-robotics',
    coverImage: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&h=400&fit=crop',
    memberCount: 156,
    visibility: 'public',
    admins: ['admin-7'],
    moderators: ['mod-10', 'mod-11'],
    rules: [
      'المشاركة في المشاريع',
      'التعلم المستمر',
      'مساعدة الأعضاء الجدد',
      'الاحترام الفني',
    ],
    centerId: '1',
  },
  {
    id: 'club-3',
    name: 'نادي الشباب والسياسة',
    description: 'منصة للحوار السياسي البناء والتوعية المدنية. مناقشات حول القضايا المحلية والوطنية، حقوق المواطن، والمشاركة السياسية.',
    category: 'politics-youth',
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=400&fit=crop',
    memberCount: 94,
    visibility: 'public',
    admins: ['admin-8'],
    moderators: ['mod-12'],
    rules: [
      'الاحترام في النقاش',
      'الابتعاد عن التمييز',
      'التركيز على الحلول البناءة',
      'احترام وجهات النظر المختلفة',
    ],
    centerId: '2',
  },
  {
    id: 'club-4',
    name: 'نادي التصوير الفوتوغرافي',
    description: 'نادي للهواة والمحترفين في التصوير. جولات تصوير، ورش تعليمية، ومعارض فوتوغرافية.',
    category: 'arts-photography',
    coverImage: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=800&h=400&fit=crop',
    memberCount: 78,
    visibility: 'public',
    admins: ['admin-9'],
    moderators: ['mod-13'],
    rules: [
      'احترام خصوصية الآخرين',
      'المشاركة في الجولات',
      'تقاسم المعرفة',
      'احترام حقوق الصور',
    ],
    centerId: '3',
  },
  {
    id: 'club-5',
    name: 'نادي ريادة الأعمال',
    description: 'نادي للشباب رواد الأعمال. نقاش الأفكار، تطوير المشاريع، واستضافة رواد أعمال ناجحين.',
    category: 'entrepreneurship',
    coverImage: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=400&fit=crop',
    memberCount: 143,
    visibility: 'public',
    admins: ['admin-10'],
    moderators: ['mod-14', 'mod-15'],
    rules: [
      'المشاركة الفعالة',
      'دعم الأفكار',
      'الشفافية',
      'التعلم المستمر',
    ],
    centerId: '1',
  },
  {
    id: 'club-6',
    name: 'نادي البيئة والاستدامة',
    description: 'نادي للشباب المهتمين بالبيئة والاستدامة. حملات تنظيف، مشاريع خضراء، وتوعية بيئية.',
    category: 'environment-sustainability',
    coverImage: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&h=400&fit=crop',
    memberCount: 112,
    visibility: 'public',
    admins: ['admin-11'],
    moderators: ['mod-16'],
    rules: [
      'الالتزام بالممارسات البيئية',
      'المشاركة في الأنشطة',
      'التوعية البيئية',
      'احترام الطبيعة',
    ],
    centerId: '2',
  },
];
